# fly.toml app configuration file generated for paymaster-app on 2024-12-31T11:55:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "paymaster-app"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
